# Generated by Django 2.1.3 on 2018-11-12 09:39

from django.db import migrations, models
import django.utils.timezone
import testapp.workflows


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lifecycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wf_state', models.CharField(choices=[('develop', 'Under Development'), ('live', 'Live'), ('maintenance', 'Under Maintenance'), ('deleted', 'Deleted')], default='develop', help_text='Workflow state', max_length=32, verbose_name='Workflow Status')),
                ('wf_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Indicates when this workflowstate was entered.', verbose_name='Workflow Date')),
            ],
            options={
                'abstract': False,
            },
            bases=(testapp.workflows.LifecycleStateMachineMixin, models.Model),
        ),
    ]
